version: '3.9'
services:
  front:
    build: ./front
    image: saidkour/testtach:front.v1
    container_name: frontend-service
    ports:
      - "8080:8080"
    volumes:
      - ./front/node_modules:/app/node_modules
  





